/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.seren.view;

import com.seren.controller.CadastroController;
import com.seren.util.ValidadorDadosUsuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class Cadastro extends javax.swing.JFrame {

    private final CadastroController controller = new CadastroController();

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/iconLogo.png")).getImage());
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailInputCadastro = new com.seren.components.RoundedJTextField(20);
        usernameInputCadastro = new com.seren.components.RoundedJTextField(20);
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senhaInputCadastro = new com.seren.components.RoundedJPasswordField(20);
        cadastroButton = new com.seren.components.RoundedButton(30);
        senhaConfirmarInputCadastro = new com.seren.components.RoundedJPasswordField(20);
        jLabel13 = new javax.swing.JLabel();
        telefoneInputCadastro = new com.seren.components.RoundedJFormattedTextField(30);
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LoginButton1 = new com.seren.components.RoundedButton(30);
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seren - Cadastro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(938, 665));
        setPreferredSize(new java.awt.Dimension(940, 665));
        setSize(new java.awt.Dimension(0, 0));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(920, 630));
        jPanel7.setPreferredSize(new java.awt.Dimension(920, 630));
        jPanel7.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 246, 248));
        jPanel2.setMinimumSize(new java.awt.Dimension(460, 630));
        jPanel2.setPreferredSize(new java.awt.Dimension(460, 630));

        jPanel6.setBackground(new java.awt.Color(255, 246, 248));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(450, 460));
        jPanel6.setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/icon/iconTelefone.png"))); // NOI18N
        jPanel6.add(jLabel17);
        jLabel17.setBounds(130, 190, 20, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/icon/iconUser.png"))); // NOI18N
        jPanel6.add(jLabel18);
        jLabel18.setBounds(130, 130, 14, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/icon/e-mail.png"))); // NOI18N
        jPanel6.add(jLabel16);
        jLabel16.setBounds(130, 250, 14, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/icon/fechadura.png"))); // NOI18N
        jPanel6.add(jLabel15);
        jLabel15.setBounds(130, 370, 16, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/icon/fechadura.png"))); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(130, 310, 16, 30);

        jLabel3.setBackground(new java.awt.Color(1, 66, 158));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 66, 158));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crie a sua conta");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(0, 41, 460, 48);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Email");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel6.add(jLabel4);
        jLabel4.setBounds(120, 230, 200, 15);

        emailInputCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailInputCadastro.setToolTipText("");
        emailInputCadastro.setMargin(new java.awt.Insets(0, 30, 0, 10));
        emailInputCadastro.setNextFocusableComponent(usernameInputCadastro);
        emailInputCadastro.setPreferredSize(new java.awt.Dimension(230, 30));
        emailInputCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputCadastroActionPerformed(evt);
            }
        });
        jPanel6.add(emailInputCadastro);
        emailInputCadastro.setBounds(120, 250, 230, 30);

        usernameInputCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameInputCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usernameInputCadastro.setMargin(new java.awt.Insets(0, 30, 0, 10));
        usernameInputCadastro.setNextFocusableComponent(telefoneInputCadastro);
        usernameInputCadastro.setPreferredSize(new java.awt.Dimension(230, 30));
        jPanel6.add(usernameInputCadastro);
        usernameInputCadastro.setBounds(120, 130, 230, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome e sobrenome");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel6.add(jLabel1);
        jLabel1.setBounds(120, 110, 200, 15);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Celular");
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel6.add(jLabel5);
        jLabel5.setBounds(120, 170, 200, 15);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Senha");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel6.add(jLabel2);
        jLabel2.setBounds(120, 290, 200, 15);

        senhaInputCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaInputCadastro.setMargin(new java.awt.Insets(0, 30, 0, 10));
        senhaInputCadastro.setNextFocusableComponent(cadastroButton);
        senhaInputCadastro.setPreferredSize(new java.awt.Dimension(230, 30));
        jPanel6.add(senhaInputCadastro);
        senhaInputCadastro.setBounds(120, 310, 230, 30);

        cadastroButton.setBackground(new java.awt.Color(1, 66, 158));
        cadastroButton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cadastroButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastroButton.setText("Criar Conta");
        cadastroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastroButton.setMinimumSize(new java.awt.Dimension(200, 40));
        cadastroButton.setPreferredSize(new java.awt.Dimension(200, 40));
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        jPanel6.add(cadastroButton);
        cadastroButton.setBounds(134, 420, 200, 40);

        senhaConfirmarInputCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senhaConfirmarInputCadastro.setMargin(new java.awt.Insets(0, 30, 0, 10));
        senhaConfirmarInputCadastro.setPreferredSize(new java.awt.Dimension(230, 30));
        jPanel6.add(senhaConfirmarInputCadastro);
        senhaConfirmarInputCadastro.setBounds(120, 370, 230, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Confirmação de senha");
        jLabel13.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel6.add(jLabel13);
        jLabel13.setBounds(120, 350, 200, 15);

        try {
            telefoneInputCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-#### ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneInputCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneInputCadastro.setMargin(new java.awt.Insets(0, 30, 0, 10));
        telefoneInputCadastro.setNextFocusableComponent(senhaInputCadastro);
        telefoneInputCadastro.setPreferredSize(new java.awt.Dimension(230, 30));
        jPanel6.add(telefoneInputCadastro);
        telefoneInputCadastro.setBounds(120, 190, 230, 30);

        jPanel2.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 246, 248));
        jPanel9.setFocusable(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(460, 158));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/LoginMenorFlip.png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jPanel2.add(jPanel9);

        jPanel7.add(jPanel2);
        jPanel2.setBounds(460, 0, 460, 630);

        jPanel10.setBackground(new java.awt.Color(255, 209, 196));
        jPanel10.setAlignmentX(0.0F);
        jPanel10.setAlignmentY(0.0F);
        jPanel10.setMaximumSize(new java.awt.Dimension(460, 630));
        jPanel10.setPreferredSize(new java.awt.Dimension(460, 630));

        jPanel12.setBackground(new java.awt.Color(255, 209, 196));

        jPanel11.setBackground(new java.awt.Color(255, 209, 196));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel11.setPreferredSize(new java.awt.Dimension(460, 190));
        jPanel11.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 66, 158));
        jLabel6.setText("Bem-vinda de volta ao ");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel6);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 66, 158));
        jLabel8.setText("Seren !");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel8);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Se conecte para gerenciar sua vida profissional ");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel7);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("de forma prática e rápida");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel10);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Já tem uma conta?");

        LoginButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LoginButton1.setForeground(new java.awt.Color(1, 66, 158));
        LoginButton1.setText("Logar-se");
        LoginButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        LoginButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton1.setMinimumSize(new java.awt.Dimension(200, 40));
        LoginButton1.setPreferredSize(new java.awt.Dimension(200, 40));
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginCadastro/LoginPlantaFlip.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LoginButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(126, 126, 126)))
                .addGap(101, 101, 101))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel10.add(jPanel12);

        jPanel7.add(jPanel10);
        jPanel10.setBounds(0, 0, 460, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputCadastroActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        String username = usernameInputCadastro.getText();
        String email = emailInputCadastro.getText();
        String telefone = telefoneInputCadastro.getText();
        String senha = new String(senhaInputCadastro.getPassword());
        String senhaConfirmar = new String(senhaConfirmarInputCadastro.getPassword());

        ValidadorDadosUsuario validador = new ValidadorDadosUsuario(username, email, telefone, senha, senhaConfirmar);
        String erro = validador.validar();

        if (erro != null) {
            JOptionPane.showMessageDialog(null, erro);
            return;
        }
        
        boolean sucesso = controller.cadastrarUsuario(username, email, telefone, senha);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
            Login login = new Login();
            login.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Usuário já foi cadastrado anteriormente.");
        }

        usernameInputCadastro.setText("");
        emailInputCadastro.setText("");
        telefoneInputCadastro.setText("");
        senhaInputCadastro.setText("");
        senhaConfirmarInputCadastro.setText("");
    }//GEN-LAST:event_cadastroButtonActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_LoginButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton1;
    private javax.swing.JButton cadastroButton;
    private javax.swing.JTextField emailInputCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField senhaConfirmarInputCadastro;
    private javax.swing.JPasswordField senhaInputCadastro;
    private javax.swing.JFormattedTextField telefoneInputCadastro;
    private javax.swing.JTextField usernameInputCadastro;
    // End of variables declaration//GEN-END:variables
}
