/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.seren.view;

import com.seren.controller.AlterarPacienteController;
import com.seren.model.Paciente;
import com.seren.model.Usuario;
import com.seren.util.ValidadorDadosPaciente;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author Pichau
 */
public class TelaEditarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaEditarPaciente() {
        initComponents();
        setResizable(false);
    }

    private AlterarPacienteController controller = new AlterarPacienteController();
    private Usuario usuario;
    private Paciente paciente;
    private TelaPacientes telaPacientes;

    public TelaEditarPaciente(Usuario usuarioLogado, Paciente paciente, TelaPacientes telaPacientes) {
        initComponents();
        this.usuario = usuarioLogado;
        this.paciente = paciente;
        this.telaPacientes = telaPacientes;

        //tirando a borda de uma tela separada
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        nomeInputEditarPaciente.setText(paciente.getNome());
        profissaoInputEditarPaciente.setText(paciente.getProfissao());
        generoInputEditarPaciente.setText(paciente.getGenero());
        estadoCivilInputEditarPaciente.setText(paciente.getEstadoCivil());
        telefoneInputEditarPaciente.setText(String.valueOf(paciente.getTelefone()));
        emailInputEditarPaciente.setText(paciente.getEmail());
        preferenciaContatoInputEditarPaciente.setText(paciente.getPreferenciaContato());
        dataNascimentoInputEditarPaciente.setDate(paciente.getDataNascimento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        profissaoInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        generoInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        estadoCivilInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        emailInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        preferenciaContatoInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataNascimentoInputEditarPaciente = new com.seren.components.RoundedJDateChooser(20);
        btnCancelarEdicao = new com.seren.components.RoundedButton(30);
        btnEditarPacientes = new com.seren.components.RoundedButton(30);
        jLabel9 = new javax.swing.JLabel();
        telefoneInputEditarPaciente = new com.seren.components.RoundedJFormattedTextField(30);

        setBackground(new java.awt.Color(102, 255, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setMinimumSize(new java.awt.Dimension(596, 428));
        setPreferredSize(new java.awt.Dimension(596, 428));

        jPanel1.setBackground(new java.awt.Color(255, 246, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(596, 428));

        nomeInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nomeInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        nomeInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        profissaoInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        profissaoInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        profissaoInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        generoInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        generoInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        generoInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        estadoCivilInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        estadoCivilInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        estadoCivilInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        emailInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        emailInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        emailInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        preferenciaContatoInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        preferenciaContatoInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        preferenciaContatoInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Gênero");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Telefone");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Profissão");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Estado Civil");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Data de Nascimento");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Preferência Contato");

        dataNascimentoInputEditarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        dataNascimentoInputEditarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));

        btnCancelarEdicao.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelarEdicao.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnCancelarEdicao.setText("Cancelar");
        btnCancelarEdicao.setPreferredSize(new java.awt.Dimension(170, 35));
        btnCancelarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEdicaoActionPerformed(evt);
            }
        });

        btnEditarPacientes.setBackground(new java.awt.Color(1, 66, 158));
        btnEditarPacientes.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnEditarPacientes.setText("Editar");
        btnEditarPacientes.setPreferredSize(new java.awt.Dimension(170, 35));
        btnEditarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacientesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 66, 158));
        jLabel9.setText("Editar paciente");

        try {
            telefoneInputEditarPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-#### ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneInputEditarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneInputEditarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        telefoneInputEditarPaciente.setPreferredSize(new java.awt.Dimension(230, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(generoInputEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(preferenciaContatoInputEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefoneInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(nomeInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataNascimentoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissaoInputEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilInputEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnCancelarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnEditarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissaoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(estadoCivilInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(generoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preferenciaContatoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacientesActionPerformed
        String nome = nomeInputEditarPaciente.getText();
        String profissao = profissaoInputEditarPaciente.getText();
        String genero = generoInputEditarPaciente.getText();
        String estadoCivil = estadoCivilInputEditarPaciente.getText();
        String telefone = telefoneInputEditarPaciente.getText();
        String email = emailInputEditarPaciente.getText();
        String preferenciaContato = preferenciaContatoInputEditarPaciente.getText();
        Date dataNascimento = dataNascimentoInputEditarPaciente.getDate();

        ValidadorDadosPaciente validador = new ValidadorDadosPaciente(nome, profissao, genero, estadoCivil, telefone, email, preferenciaContato, dataNascimento);
        String erro = validador.validar();

        if (erro != null) {
            JOptionPane.showMessageDialog(null, erro);
            return;
        }

        long telefoneNumero = validador.getTelefone();

        paciente.setNome(nome);
        paciente.setProfissao(profissao);
        paciente.setGenero(genero);
        paciente.setEstadoCivil(estadoCivil);
        paciente.setTelefone(telefoneNumero);
        paciente.setEmail(email);
        paciente.setPreferenciaContato(preferenciaContato);
        paciente.setDataNascimento(dataNascimento);

        boolean sucesso = controller.alterarPaciente(paciente);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Paciente alterado com sucesso!");
            telaPacientes.carregarPacientesNaTabela();
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Insira dados novos.");
        }
    }//GEN-LAST:event_btnEditarPacientesActionPerformed

    private void btnCancelarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicaoActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelarEdicaoActionPerformed
    
    //metrodo para centraliar
    public void centralizar() {
        if (getParent() != null) {
            this.setLocation(
                    (getParent().getWidth() - this.getWidth()) / 2,
                    (getParent().getHeight() - this.getHeight()) / 2
            );
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEdicao;
    private javax.swing.JButton btnEditarPacientes;
    private com.toedter.calendar.JDateChooser dataNascimentoInputEditarPaciente;
    private javax.swing.JTextField emailInputEditarPaciente;
    private javax.swing.JTextField estadoCivilInputEditarPaciente;
    private javax.swing.JTextField generoInputEditarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeInputEditarPaciente;
    private javax.swing.JTextField preferenciaContatoInputEditarPaciente;
    private javax.swing.JTextField profissaoInputEditarPaciente;
    private javax.swing.JFormattedTextField telefoneInputEditarPaciente;
    // End of variables declaration//GEN-END:variables
}
