/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.seren.view;

import com.seren.controller.BuscarPacienteController;
import com.seren.controller.BuscarPacientesController;
import com.seren.controller.ExcluirPacienteController;
import com.seren.model.Paciente;
import com.seren.model.Usuario;
import com.seren.util.DataUtil;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

import javax.swing.plaf.basic.BasicInternalFrameUI;

import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author Pichau
 */
public class TelaPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pacientes
     */
    public TelaPacientes() {
        initComponents();
        setResizable(false);

    }

    private Usuario usuario;

    BuscarPacientesController controller = new BuscarPacientesController();

    BuscarPacientesController buscarPacientesController = new BuscarPacientesController();
    BuscarPacienteController buscarPacienteController = new BuscarPacienteController();
    private ArrayList<Document> listaPacientes = new ArrayList<>();
    ExcluirPacienteController excluirPacienteController = new ExcluirPacienteController();

    private JPopupMenu menuPopup;
    private JMenuItem menuEditar;
    private JMenuItem menuExcluir;

    public TelaPacientes(Usuario usuarioLogado) {
        initComponents();
        this.usuario = usuarioLogado;
        exibirInfoUsuario();

        //tirando a borda de uma tela separada
        this.setBorder(null);
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        criarMenuPopup();
        adicionarListenerTabela();
        carregarPacientesNaTabela();
        // Listener para detectar mudanças no campo de busca
        buscarInputBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                String textoBusca = buscarInputBuscarPaciente.getText().trim();
                if (textoBusca.isEmpty()) {
                    carregarPacientesNaTabela(); // carrega todos os pacientes automaticamente
                }
            }
        });
    }

    public void carregarPacientesNaTabela() {
        carregarPacientesNaTabela(null);
    }

    public void carregarPacientesNaTabela(String filtroNome) {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Nome");
        modelo.addColumn("Idade");
        modelo.addColumn("Email");

        if (filtroNome == null || filtroNome.isEmpty()) {
            listaPacientes = buscarPacientesController.buscarPacientes(usuario.getId());
        } else {
            listaPacientes = buscarPacienteController.buscarPacientes(usuario.getId(), filtroNome);
        }

        if (!listaPacientes.isEmpty()) {
            for (Document doc : listaPacientes) {
                String nomePaciente = doc.getString("nome");
                Date dataNascimento = doc.getDate("dataNascimento");
                int idade = DataUtil.calcularIdade(dataNascimento);
                String email = doc.getString("email");
                modelo.addRow(new Object[]{nomePaciente, idade, email});
            }
        } else {
            modelo.addRow(new Object[]{"Nenhum paciente encontrado", "", ""});
        }

        tabelaPacientes.setModel(modelo);

        JTableHeader cabecalho = tabelaPacientes.getTableHeader();
        cabecalho.setFont(new Font("Segoe UI Ligth", Font.BOLD, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        btnBuscarPacienteNome = new com.seren.components.RoundedButton(30);
        buscarInputBuscarPaciente = new com.seren.components.RoundedJFormattedTextField(30);
        labelNomeUsuario = new javax.swing.JLabel();
        labelEmailUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPacientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarPaciente = new com.seren.components.RoundedButton(30);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(700, 630));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));

        jDesktopPane2.setBackground(new java.awt.Color(255, 246, 248));

        jPanel2.setBackground(new java.awt.Color(255, 246, 248));
        jPanel2.setLayout(null);

        btnBuscarPacienteNome.setBackground(new java.awt.Color(1, 66, 158));
        btnBuscarPacienteNome.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnBuscarPacienteNome.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPacienteNome.setText("Buscar");
        btnBuscarPacienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteNomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarPacienteNome);
        btnBuscarPacienteNome.setBounds(310, 30, 90, 40);

        buscarInputBuscarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        buscarInputBuscarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        buscarInputBuscarPaciente.setForeground(new java.awt.Color(0, 0, 0));
        buscarInputBuscarPaciente.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 10));
        buscarInputBuscarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        buscarInputBuscarPaciente.setMinimumSize(new java.awt.Dimension(390, 40));
        buscarInputBuscarPaciente.setPreferredSize(new java.awt.Dimension(390, 40));
        jPanel2.add(buscarInputBuscarPaciente);
        buscarInputBuscarPaciente.setBounds(10, 30, 390, 40);

        labelNomeUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        labelNomeUsuario.setText("Nome usuario");
        jPanel2.add(labelNomeUsuario);
        labelNomeUsuario.setBounds(550, 30, 140, 16);

        labelEmailUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        labelEmailUsuario.setText("Email usuario");
        labelEmailUsuario.setPreferredSize(new java.awt.Dimension(94, 20));
        jPanel2.add(labelEmailUsuario);
        labelEmailUsuario.setBounds(550, 50, 140, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfilUsuario.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(480, 20, 60, 60);

        tabelaPacientes.setAutoCreateRowSorter(true);
        tabelaPacientes.setBackground(new java.awt.Color(255, 246, 248));
        tabelaPacientes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tabelaPacientes.setForeground(new java.awt.Color(0, 0, 0));
        tabelaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaPacientes.setRowHeight(50);
        tabelaPacientes.setRowSorter(null);
        tabelaPacientes.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tabelaPacientes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabelaPacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPacientes.setShowGrid(false);
        jScrollPane1.setViewportView(tabelaPacientes);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 66, 158));
        jLabel1.setText("Pacientes");

        btnCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnCadastrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userplus.png"))); // NOI18N
        btnCadastrarPaciente.setText("Adicionar paciente");
        btnCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacienteActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnCadastrarPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(btnCadastrarPaciente)))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibirInfoUsuario() {
        labelNomeUsuario.setText(usuario.getNome());
        labelEmailUsuario.setText(usuario.getEmail());
    }

    private void criarMenuPopup() {
        menuPopup = new JPopupMenu();

        menuEditar = new JMenuItem("Editar");

        menuExcluir = new JMenuItem("Excluir");

        menuPopup.add(menuEditar);
        menuPopup.add(menuExcluir);

        menuEditar.addActionListener(e -> editarPacienteSelecionado());
        menuExcluir.addActionListener(e -> excluirPacienteSelecionado());

    }

    private void adicionarListenerTabela() {
        tabelaPacientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    mostrarMenuPopup(e);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    mostrarMenuPopup(e);
                }
            }
        });
    }

    private void mostrarMenuPopup(MouseEvent e) {
        int row = tabelaPacientes.rowAtPoint(e.getPoint());
        if (row >= 0 && row < listaPacientes.size()) {
            tabelaPacientes.setRowSelectionInterval(row, row);
            menuPopup.show(e.getComponent(), e.getX(), e.getY());
        }
    }

    private void editarPacienteSelecionado() {
        int row = tabelaPacientes.getSelectedRow();
        if (row >= 0 && row < listaPacientes.size()) {
            Document docSelecionado = listaPacientes.get(row);
            Paciente paciente = Paciente.pacienteDocumento(docSelecionado);
            TelaEditarPaciente telaEditar = new TelaEditarPaciente(this.usuario, paciente, this);
            jDesktopPane2.add(telaEditar);
            telaEditar.setVisible(true);
            telaEditar.centralizar(); //centralizando o jInternal que vem

        }
    }

    private void excluirPacienteSelecionado() {
        int row = tabelaPacientes.getSelectedRow();
        if (row >= 0 && row < listaPacientes.size()) {
            Document docSelecionado = listaPacientes.get(row);
            Paciente paciente = Paciente.pacienteDocumento(docSelecionado);

            int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja excluir o paciente " + paciente.getNome() + " ?",
                    "Confirmar exclusão",
                    JOptionPane.YES_NO_OPTION
            );
            if (resposta == JOptionPane.YES_OPTION) {
                boolean sucesso = excluirPacienteController.excluirPaciente(paciente.getId());
                if (sucesso) {
                    JOptionPane.showMessageDialog(null, "Paciente excluído com sucesso.");
                    carregarPacientesNaTabela();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir o paciente.");
                }
            }
        }
    }

    private void btnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacienteActionPerformed
        TelaCadastrarPaciente cadastrarPaciente = new TelaCadastrarPaciente(this.usuario, this);
        jDesktopPane2.add(cadastrarPaciente);
        cadastrarPaciente.setVisible(true);
        cadastrarPaciente.centralizar(); //centralizando o jInternal que vem
    }//GEN-LAST:event_btnCadastrarPacienteActionPerformed

    private void btnBuscarPacienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteNomeActionPerformed
        // TODO add your handling code here:
        String nome = buscarInputBuscarPaciente.getText();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio, insira o nome do paciente.");
            carregarPacientesNaTabela();
            return;
        }
        carregarPacientesNaTabela(nome);
    }//GEN-LAST:event_btnBuscarPacienteNomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPacienteNome;
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JTextField buscarInputBuscarPaciente;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmailUsuario;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JTable tabelaPacientes;
    // End of variables declaration//GEN-END:variables

}
