/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.seren.view;

import com.seren.controller.AlterarPacienteController;
import com.seren.model.Paciente;
import com.seren.model.Usuario;
import java.util.Date;
import javax.swing.JOptionPane;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author Pichau
 */
public class TelaEditarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaEditarPaciente() {
        initComponents();
    }

    private AlterarPacienteController controller = new AlterarPacienteController();
    private Usuario usuario;
    private Paciente paciente;
    private TelaPacientes telaPacientes;

    public TelaEditarPaciente(Usuario usuarioLogado, Paciente paciente, TelaPacientes telaPacientes) {
        initComponents();
        this.usuario = usuarioLogado;
        this.paciente = paciente;
        this.telaPacientes = telaPacientes;
        nomeInputEditarPaciente.setText(paciente.getNome());
        profissaoInputEditarPaciente.setText(paciente.getProfissao());
        generoInputEditarPaciente.setText(paciente.getGenero());
        estadoCivilInputEditarPaciente.setText(paciente.getEstadoCivil());
        telefoneInputEditarPaciente.setText(String.valueOf(paciente.getTelefone()));
        emailInputEditarPaciente.setText(paciente.getEmail());
        preferenciaContatoInputEditarPaciente.setText(paciente.getPreferenciaContato());
        dataNascimentoInputEditarPaciente.setDate(paciente.getDataNascimento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeInputEditarPaciente = new javax.swing.JTextField();
        profissaoInputEditarPaciente = new javax.swing.JTextField();
        generoInputEditarPaciente = new javax.swing.JTextField();
        estadoCivilInputEditarPaciente = new javax.swing.JTextField();
        emailInputEditarPaciente = new javax.swing.JTextField();
        preferenciaContatoInputEditarPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataNascimentoInputEditarPaciente = new com.toedter.calendar.JDateChooser();
        telefoneInputEditarPaciente = new javax.swing.JFormattedTextField();
        editarPacientesButton = new javax.swing.JButton();

        nomeInputEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeInputEditarPacienteActionPerformed(evt);
            }
        });

        preferenciaContatoInputEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciaContatoInputEditarPacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Gênero");

        jLabel3.setText("Telefone");

        jLabel4.setText("Profissão");

        jLabel5.setText("Estado Civil");

        jLabel6.setText("Email");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Preferência Contato");

        telefoneInputEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneInputEditarPacienteActionPerformed(evt);
            }
        });

        editarPacientesButton.setText("Editar");
        editarPacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPacientesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preferenciaContatoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(generoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nomeInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(telefoneInputEditarPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailInputEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(estadoCivilInputEditarPaciente)
                            .addComponent(profissaoInputEditarPaciente))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(dataNascimentoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(editarPacientesButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissaoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(emailInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefoneInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataNascimentoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preferenciaContatoInputEditarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(editarPacientesButton)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeInputEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeInputEditarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeInputEditarPacienteActionPerformed

    private void preferenciaContatoInputEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciaContatoInputEditarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferenciaContatoInputEditarPacienteActionPerformed

    private void telefoneInputEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneInputEditarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneInputEditarPacienteActionPerformed

    private void editarPacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPacientesButtonActionPerformed
        String nome = nomeInputEditarPaciente.getText();
        String profissao = profissaoInputEditarPaciente.getText();
        String genero = generoInputEditarPaciente.getText();
        String estadoCivil = estadoCivilInputEditarPaciente.getText();
        String telefone = telefoneInputEditarPaciente.getText();
        String email = emailInputEditarPaciente.getText();
        String preferenciaContato = preferenciaContatoInputEditarPaciente.getText();
        Date dataNascimento = dataNascimentoInputEditarPaciente.getDate();

        telefone = telefone.replaceAll("[^\\d]", ""); // remove tudo que não for número

        if (nome.isEmpty() || profissao.isEmpty() || genero.isEmpty() || estadoCivil.isEmpty()
                || telefone.isEmpty() || email.isEmpty() || preferenciaContato.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            return;
        } else if (!email.contains("@")) {
            JOptionPane.showMessageDialog(null, "Insira um email válido!");
            return;
        } else if (telefone.length() != 11) {
            JOptionPane.showMessageDialog(null, "Insira um número de telefone válido");
            return;
        }

        long telefoneNumero;
        try {
            telefoneNumero = Long.parseLong(telefone);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Número de telefone inválido.");
            return;
        }

        paciente.setNome(nome);
        paciente.setProfissao(profissao);
        paciente.setGenero(genero);
        paciente.setEstadoCivil(estadoCivil);
        paciente.setTelefone(telefoneNumero);
        paciente.setEmail(email);
        paciente.setPreferenciaContato(preferenciaContato);
        paciente.setDataNascimento(dataNascimento);

        boolean sucesso = controller.alterarPaciente(paciente);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Paciente alterado com sucesso!");
            telaPacientes.carregarPacientesNaTabela();
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Insira dados novos.");
        }
    }//GEN-LAST:event_editarPacientesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dataNascimentoInputEditarPaciente;
    private javax.swing.JButton editarPacientesButton;
    private javax.swing.JTextField emailInputEditarPaciente;
    private javax.swing.JTextField estadoCivilInputEditarPaciente;
    private javax.swing.JTextField generoInputEditarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeInputEditarPaciente;
    private javax.swing.JTextField preferenciaContatoInputEditarPaciente;
    private javax.swing.JTextField profissaoInputEditarPaciente;
    private javax.swing.JFormattedTextField telefoneInputEditarPaciente;
    // End of variables declaration//GEN-END:variables
}
