/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.seren.view;

import com.seren.model.Usuario;
import javax.swing.ImageIcon;
import com.seren.components.RoundedPanel;
import com.seren.controller.BuscarPacientesController;
import javax.swing.JOptionPane;
import com.seren.util.LembrarEmailUtil;
import java.util.ArrayList;
import org.bson.Document;

/**
 *
 * @author Pichau
 */
public class TelaInicial extends javax.swing.JFrame {

    private TelaPacientes telaPacientes;

    /**
     * Creates new form PaginaInicial
     */
    public TelaInicial() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/iconLogo.png")).getImage());
        setResizable(false);
    }

    private Usuario usuario;
    private boolean lembrarEmail;

    public TelaInicial(Usuario usuarioLogado, boolean lembrarEmail) {
        initComponents();
        this.usuario = usuarioLogado;
        this.lembrarEmail = lembrarEmail;
        exibirSaudacao();
        totalPacientesCadastrados();

        labelSerengotoInitialScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (telaPacientes != null && telaPacientes.isVisible()) {
                    try {
                        telaPacientes.setClosed(true);
                        telaPacientes = null;
                        totalPacientesCadastrados();
                    } catch (java.beans.PropertyVetoException e) {
                        e.printStackTrace();
                    }
                }
            }
        });

        labelSerengotoInitialScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelSairgotoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (!lembrarEmail) {
                    LembrarEmailUtil.excluirEmail();
                }

                Login login = new Login();
                JOptionPane.showMessageDialog(null, "Sessão encerrada!");
                login.setVisible(true);
                setVisible(false);
            }
        });

        labelSairgotoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButtonActionPerformed(evt);
            }
        });

    }

    private void exibirSaudacao() {
        String saudacao;
        int hora = java.time.LocalTime.now().getHour();

        if (hora >= 5 && hora < 12) {
            saudacao = "Bom dia";
        } else if (hora >= 12 && hora < 18) {
            saudacao = "Boa tarde";
        } else {
            saudacao = "Boa noite";
        }

        labelApresentarUsername.setText(saudacao + ", " + usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        labelApresentarUsername = new javax.swing.JLabel();
        jPanel3 = new com.seren.components.RoundedPanel(30);
        jPanel8 = new com.seren.components.RoundedPanel(40);
        labelTotalPacientes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new com.seren.components.RoundedPanel(30);
        jCalendar1 = new com.seren.components.CustomJCalendar();
        jPanel6 = new com.seren.components.RoundedPanel(30);
        jLabel1 = new javax.swing.JLabel();
        pacientesButton = new com.seren.components.RoundedButton(20);
        jPanel2 = new javax.swing.JPanel();
        labelSerengotoInitialScreen = new javax.swing.JLabel();
        jPanel7 = new com.seren.components.RoundedPanel(30);
        labelSairgotoLogin = new javax.swing.JLabel();
        labelSerentoMeuPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seren - Tela inicial");
        setBackground(new java.awt.Color(51, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 630));
        jPanel1.setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(255, 246, 248));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labelApresentarUsername.setBackground(new java.awt.Color(255, 246, 248));
        labelApresentarUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        labelApresentarUsername.setForeground(new java.awt.Color(0, 0, 0));
        labelApresentarUsername.setText("Bom dia, Usuário!");

        jPanel3.setBackground(new java.awt.Color(255, 246, 248));
        jPanel3.setForeground(new java.awt.Color(204, 255, 153));
        jPanel3.setToolTipText("");
        jPanel3.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel3.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setFocusable(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(675, 95));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setVerifyInputWhenFocusTarget(false);

        labelTotalPacientes.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        labelTotalPacientes.setForeground(new java.awt.Color(0, 0, 0));
        labelTotalPacientes.setText("Total Pacientes Cadastrados");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTotalPacientes)
                .addGap(130, 130, 130))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTotalPacientes)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 20, 700, 90);

        jPanel5.setBackground(new java.awt.Color(225, 225, 225));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(330, 330));

        jCalendar1.setDate(new java.util.Date(1749130444000L));
        jCalendar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(255, 255, 255));
        jCalendar1.setDoubleBuffered(false);
        jCalendar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCalendar1.setMaximumSize(new java.awt.Dimension(200, 300));
        jCalendar1.setMinSelectableDate(new java.util.Date(-62135755081000L));
        jCalendar1.setMinimumSize(new java.awt.Dimension(200, 300));
        jCalendar1.setOpaque(true);
        jCalendar1.setPreferredSize(new java.awt.Dimension(340, 300));
        jCalendar1.setRequestFocusEnabled(false);
        jCalendar1.setSundayForeground(new java.awt.Color(0, 51, 255));
        jCalendar1.setTodayButtonText("");
        jCalendar1.setVerifyInputWhenFocusTarget(false);
        jCalendar1.setWeekOfYearVisible(false);
        jCalendar1.setWeekdayForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(350, 130, 350, 330);

        jPanel6.setBackground(new java.awt.Color(250, 186, 197));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(330, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pacientes.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(190, 190));

        pacientesButton.setBackground(new java.awt.Color(255, 255, 255));
        pacientesButton.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        pacientesButton.setForeground(new java.awt.Color(0, 0, 0));
        pacientesButton.setText("Pacientes");
        pacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(pacientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pacientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 130, 330, 330);

        jDesktopPane1.setLayer(labelApresentarUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelApresentarUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelApresentarUsername)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(200, 0, 740, 630);

        jPanel2.setBackground(new java.awt.Color(255, 246, 248));
        jPanel2.setLayout(null);

        labelSerengotoInitialScreen.setBackground(new java.awt.Color(1, 66, 158));
        labelSerengotoInitialScreen.setFont(new java.awt.Font("Segoe Script", 0, 48)); // NOI18N
        labelSerengotoInitialScreen.setForeground(new java.awt.Color(1, 66, 158));
        labelSerengotoInitialScreen.setText("Seren");
        labelSerengotoInitialScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(labelSerengotoInitialScreen);
        labelSerengotoInitialScreen.setBounds(24, 17, 150, 77);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        labelSairgotoLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        labelSairgotoLogin.setForeground(new java.awt.Color(255, 51, 51));
        labelSairgotoLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSairgotoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log out.png"))); // NOI18N
        labelSairgotoLogin.setText("Sair");
        labelSairgotoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSairgotoLogin.setIconTextGap(10);

        labelSerentoMeuPerfil.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        labelSerentoMeuPerfil.setForeground(new java.awt.Color(0, 0, 0));
        labelSerentoMeuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        labelSerentoMeuPerfil.setText(" Meu Pefil");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSairgotoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSerentoMeuPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(labelSerentoMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(labelSairgotoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(14, 100, 168, 512);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButtonActionPerformed
        // TODO add your handling code here:
        if (telaPacientes == null || telaPacientes.isClosed()) {
            telaPacientes = new TelaPacientes(this.usuario);
            jDesktopPane1.add(telaPacientes);
            telaPacientes.setVisible(true);
            setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/iconLogo.png")).getImage());
            setResizable(false);
        }
    }//GEN-LAST:event_pacientesButtonActionPerformed

    private void totalPacientesCadastrados() {
        BuscarPacientesController controller = new BuscarPacientesController();
        ArrayList<Document> pacientes = controller.buscarPacientes(usuario.getId());
        labelTotalPacientes.setText(pacientes.size() + " pacientes cadastrados");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelApresentarUsername;
    private javax.swing.JLabel labelSairgotoLogin;
    private javax.swing.JLabel labelSerengotoInitialScreen;
    private javax.swing.JLabel labelSerentoMeuPerfil;
    private javax.swing.JLabel labelTotalPacientes;
    private javax.swing.JButton pacientesButton;
    // End of variables declaration//GEN-END:variables
}
