/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.seren.view;

import com.seren.controller.CriarPacienteController;
import com.seren.model.Usuario;
import com.seren.util.ValidadorDadosPaciente;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.bson.types.ObjectId;

/**
 *
 * @author Pichau
 */
public class TelaCadastrarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarPaciente
     */
    
    private CriarPacienteController controller = new CriarPacienteController();
    
    public TelaCadastrarPaciente() {
        initComponents();
        setResizable(false);
    }
    
    private Usuario usuario;
    private TelaPacientes telaPacientes;
    
    public TelaCadastrarPaciente(Usuario usuarioLogado, TelaPacientes telaPacientes){
        initComponents();
        this.usuario = usuarioLogado;
        this.telaPacientes = telaPacientes;
        
        //tirando a borda de uma tela separada
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomeInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(30);
        profissaoInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(30);
        generoInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(30);
        estadoCivilInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        emailInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(30);
        preferenciaContatoInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(20);
        dataNascimentoInputCadastrarPaciente = new com.seren.components.RoundedJDateChooser(20);
        cadastrarPacientesButton = new com.seren.components.RoundedButton(30);
        jButton1 = new com.seren.components.RoundedButton(30);
        jLabel9 = new javax.swing.JLabel();
        telefoneInputCadastrarPaciente = new com.seren.components.RoundedJFormattedTextField(30);

        setBackground(new java.awt.Color(153, 153, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setMinimumSize(new java.awt.Dimension(596, 428));
        setPreferredSize(new java.awt.Dimension(596, 428));

        jPanel1.setBackground(new java.awt.Color(255, 246, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(596, 428));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 50, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Gênero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 140, 47, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Telefone");
        jLabel3.setMaximumSize(new java.awt.Dimension(55, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(55, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(55, 14));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 69, 14);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Profissão");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 70, 70, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Estado Civil");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(306, 144, 80, 17);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Email");
        jLabel6.setMaximumSize(new java.awt.Dimension(34, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(34, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 14));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 210, 40, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Data de Nascimento");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 290, 130, 14);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Preferência Contato");
        jLabel8.setMaximumSize(new java.awt.Dimension(127, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(127, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(127, 14));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 290, 135, 14);

        nomeInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        nomeInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        nomeInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(nomeInputCadastrarPaciente);
        nomeInputCadastrarPaciente.setBounds(20, 100, 260, 35);

        profissaoInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        profissaoInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        profissaoInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(profissaoInputCadastrarPaciente);
        profissaoInputCadastrarPaciente.setBounds(310, 100, 260, 35);

        generoInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        generoInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        generoInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(generoInputCadastrarPaciente);
        generoInputCadastrarPaciente.setBounds(20, 170, 260, 35);

        estadoCivilInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        estadoCivilInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        estadoCivilInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(estadoCivilInputCadastrarPaciente);
        estadoCivilInputCadastrarPaciente.setBounds(310, 170, 260, 35);

        emailInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        emailInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        emailInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(emailInputCadastrarPaciente);
        emailInputCadastrarPaciente.setBounds(310, 240, 260, 35);

        preferenciaContatoInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        preferenciaContatoInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        preferenciaContatoInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(preferenciaContatoInputCadastrarPaciente);
        preferenciaContatoInputCadastrarPaciente.setBounds(20, 310, 260, 35);

        dataNascimentoInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        dataNascimentoInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(dataNascimentoInputCadastrarPaciente);
        dataNascimentoInputCadastrarPaciente.setBounds(310, 310, 260, 35);

        cadastrarPacientesButton.setBackground(new java.awt.Color(1, 66, 158));
        cadastrarPacientesButton.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cadastrarPacientesButton.setText("Cadastrar");
        cadastrarPacientesButton.setPreferredSize(new java.awt.Dimension(170, 35));
        cadastrarPacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacientesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarPacientesButton);
        cadastrarPacientesButton.setBounds(359, 378, 170, 35);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.setPreferredSize(new java.awt.Dimension(170, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(63, 378, 170, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 66, 158));
        jLabel9.setText("Adicionar novo paciente");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(165, 18, 260, 32);

        try {
            telefoneInputCadastrarPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-#### ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneInputCadastrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneInputCadastrarPaciente.setMargin(new java.awt.Insets(0, 10, 0, 10));
        telefoneInputCadastrarPaciente.setPreferredSize(new java.awt.Dimension(260, 35));
        jPanel1.add(telefoneInputCadastrarPaciente);
        telefoneInputCadastrarPaciente.setBounds(20, 240, 260, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarPacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacientesButtonActionPerformed
        // TODO add your handling code here:
        String nome = nomeInputCadastrarPaciente.getText();
        String profissao = profissaoInputCadastrarPaciente.getText();
        String genero = generoInputCadastrarPaciente.getText();
        String estadoCivil = estadoCivilInputCadastrarPaciente.getText();
        String telefoneFormatado = telefoneInputCadastrarPaciente.getText();
        String email = emailInputCadastrarPaciente.getText();
        String preferenciaContato = preferenciaContatoInputCadastrarPaciente.getText();
        Date dataNascimento = dataNascimentoInputCadastrarPaciente.getDate();
        ObjectId id_usuario = usuario.getId();
        
        String telefone = telefoneFormatado.replaceAll("[^\\d]", "");
        
        ValidadorDadosPaciente validador = new ValidadorDadosPaciente(nome, profissao, genero, estadoCivil, telefone, email, preferenciaContato, dataNascimento);
        String erro = validador.validar();
        
        if(erro != null){
            JOptionPane.showMessageDialog(null, erro);
            return;
        }
        
        boolean sucesso = controller.criarPaciente(nome, profissao, genero, estadoCivil, telefone, email, preferenciaContato, dataNascimento, id_usuario);
        
        if(sucesso){
            JOptionPane.showMessageDialog(null, "Paciente cadastrado com sucesso!");
            setVisible(false);
            telaPacientes.carregarPacientesNaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Paciente já cadastrado anteriormente");
        }
    }//GEN-LAST:event_cadastrarPacientesButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    //metrodo para centraliar
    public void centralizar() {
    if (getParent() != null) {
        this.setLocation(
            (getParent().getWidth() - this.getWidth()) / 2,
            (getParent().getHeight() - this.getHeight()) / 2
        );
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarPacientesButton;
    private com.toedter.calendar.JDateChooser dataNascimentoInputCadastrarPaciente;
    private javax.swing.JTextField emailInputCadastrarPaciente;
    private javax.swing.JTextField estadoCivilInputCadastrarPaciente;
    private javax.swing.JTextField generoInputCadastrarPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeInputCadastrarPaciente;
    private javax.swing.JTextField preferenciaContatoInputCadastrarPaciente;
    private javax.swing.JTextField profissaoInputCadastrarPaciente;
    private javax.swing.JFormattedTextField telefoneInputCadastrarPaciente;
    // End of variables declaration//GEN-END:variables
}
