/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.seren.view;

import com.seren.controller.CriarPacienteController;
import com.seren.model.Usuario;
import java.util.Date;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Pichau
 */
public class TelaCadastrarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarPaciente
     */
    
    private CriarPacienteController controller = new CriarPacienteController();
    
    public TelaCadastrarPaciente() {
        initComponents();
    }
    private Usuario usuario;
    private TelaPacientes telaPacientes;
    
    public TelaCadastrarPaciente(Usuario usuarioLogado, TelaPacientes telaPacientes){
        initComponents();
        this.usuario = usuarioLogado;
        this.telaPacientes = telaPacientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeInputCadastrarPaciente = new javax.swing.JTextField();
        profissaoInputCadastrarPaciente = new javax.swing.JTextField();
        generoInputCadastrarPaciente = new javax.swing.JTextField();
        estadoCivilInputCadastrarPaciente = new javax.swing.JTextField();
        emailInputCadastrarPaciente = new javax.swing.JTextField();
        preferenciaContatoInputCadastrarPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataNascimentoInputCadastrarPaciente = new com.toedter.calendar.JDateChooser();
        telefoneInputCadastrarPaciente = new javax.swing.JFormattedTextField();
        cadastrarPacientesButton = new javax.swing.JButton();

        nomeInputCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeInputCadastrarPacienteActionPerformed(evt);
            }
        });

        preferenciaContatoInputCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciaContatoInputCadastrarPacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Gênero");

        jLabel3.setText("Telefone");

        jLabel4.setText("Profissão");

        jLabel5.setText("Estado Civil");

        jLabel6.setText("Email");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Preferência Contato");

        telefoneInputCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneInputCadastrarPacienteActionPerformed(evt);
            }
        });

        cadastrarPacientesButton.setText("Cadastrar");
        cadastrarPacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacientesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preferenciaContatoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(generoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nomeInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(telefoneInputCadastrarPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailInputCadastrarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(estadoCivilInputCadastrarPaciente)
                            .addComponent(profissaoInputCadastrarPaciente))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(dataNascimentoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(cadastrarPacientesButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profissaoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(emailInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefoneInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataNascimentoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preferenciaContatoInputCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(cadastrarPacientesButton)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preferenciaContatoInputCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciaContatoInputCadastrarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferenciaContatoInputCadastrarPacienteActionPerformed

    private void cadastrarPacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacientesButtonActionPerformed
        // TODO add your handling code here:
        String nome = nomeInputCadastrarPaciente.getText();
        String profissao = profissaoInputCadastrarPaciente.getText();
        String genero = generoInputCadastrarPaciente.getText();
        String estadoCivil = estadoCivilInputCadastrarPaciente.getText();
        String telefone = telefoneInputCadastrarPaciente.getText();
        String email = emailInputCadastrarPaciente.getText();
        String preferenciaContato = preferenciaContatoInputCadastrarPaciente.getText();
        Date dataNascimento = dataNascimentoInputCadastrarPaciente.getDate();
        ObjectId id_usuario = usuario.getId();
        telefone = telefone.replaceAll("[^\\d]", "");
        
        if(nome.isEmpty() || profissao.isEmpty() || genero.isEmpty() || estadoCivil.isEmpty() || telefone.isEmpty() || email.isEmpty() || preferenciaContato.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            return;
        } else if(!email.contains("@")){
            JOptionPane.showMessageDialog(null, "Insira um email válido!");
            return;
        } else if(telefone.length() < 11 || telefone.length() > 11) {
            JOptionPane.showMessageDialog(null, "Insira um número de telefone válido");
            return;
        } 
        
        boolean sucesso = controller.criarPaciente(nome, profissao, genero, estadoCivil, telefone, email, preferenciaContato, dataNascimento, id_usuario);
        if(sucesso){
            JOptionPane.showMessageDialog(null, "Paciente cadastrado com sucesso!");
            setVisible(false);
            telaPacientes.carregarPacientesNaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Paciente já cadastrado anteriormente");
        }
    }//GEN-LAST:event_cadastrarPacientesButtonActionPerformed

    private void nomeInputCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeInputCadastrarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeInputCadastrarPacienteActionPerformed

    private void telefoneInputCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneInputCadastrarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneInputCadastrarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarPacientesButton;
    private com.toedter.calendar.JDateChooser dataNascimentoInputCadastrarPaciente;
    private javax.swing.JTextField emailInputCadastrarPaciente;
    private javax.swing.JTextField estadoCivilInputCadastrarPaciente;
    private javax.swing.JTextField generoInputCadastrarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeInputCadastrarPaciente;
    private javax.swing.JTextField preferenciaContatoInputCadastrarPaciente;
    private javax.swing.JTextField profissaoInputCadastrarPaciente;
    private javax.swing.JFormattedTextField telefoneInputCadastrarPaciente;
    // End of variables declaration//GEN-END:variables
}
